# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

variables:
- group: Variable-Group
- group: Key-Vault-Group

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
        echo "Building container.."
        docker build -t registry.gcp0001.us-east4.astronomer.io/geocentric-neutron-9870/airflow:$CI_PIPELINE_ID .
        docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(DEPLOYMENT-SERVICE-ACCOUNT-KEY1)
        docker push registry.gcp0001.us-east4.astronomer.io/geocentric-neutron-9870/airflow:$CI_PIPELINE_ID



#steps:
#- script: |
#    echo "Building container.."
#    docker build -t registry.gcp0001.us-east4.astronomer.io/geocentric-neutron-9870/airflow:$CI_PIPELINE_ID .
#    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(DEPLOYMENT-SERVICE-ACCOUNT-KEY)
#    docker push registry.gcp0001.us-east4.astronomer.io/geocentric-neutron-9870/airflow:$CI_PIPELINE_ID
