# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
 
variables:
  DEPLOYMENT-SERVICE-ACCOUNT-KEY: 'ea3e9760e18a96a472f7d90a6f3a5ceb'
  
#- group: Variable-Group
#- group: Key-Vault-Group
steps:
- script: |
    echo "Building container.."
    docker build -t registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:latest .
    docker login registry.gcp0001.us-east4.astronomer.io -u _ -p $(DEPLOYMENT-SERVICE-ACCOUNT-KEY)
    docker push registry.gcp0001.us-east4.astronomer.io/extraterrestrial-aperature-9667/airflow:latest
